version: '3'
services:
  marvelodb:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=flykite123

  marvelo:
    image: prestashop/prestashop
    ports:
      - 8080:80
    environment:
      - DB_SERVER=marvelodb 
